config/routes.rb
Rails.application.routes.draw do
  resources :patterns

end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :only => []

  # GET /patterns
  # GET /patterns.json
  def index
    @patterns = Pattern.all
    render json: @patterns
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
    render json: @pattern
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)

    if @pattern.save
      render json: @pattern
    else
      render json: @pattern.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { render :show, status: :ok, location: @pattern }
      else
        format.html { render :edit }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url, notice: 'Pattern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:p1, :p2, :p3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatternLabApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patterns/_form.html.erb
<%= form_for(@pattern) do |f| %>
  <% if @pattern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

      <ul>
      <% @pattern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :p1 %><br>
    <%= f.number_field :p1 %>
  </div>
  <div class="field">
    <%= f.label :p2 %><br>
    <%= f.number_field :p2 %>
  </div>
  <div class="field">
    <%= f.label :p3 %><br>
    <%= f.number_field :p3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patterns/edit.html.erb
<h1>Editing pattern</h1>

<%= render 'form' %>

<%= link_to 'Show', @pattern %> |
<%= link_to 'Back', patterns_path %>

app/views/patterns/index.html.erb
<h1>Listing patterns</h1>

<table>
  <thead>
    <tr>
      <th>P1</th>
      <th>P2</th>
      <th>P3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patterns.each do |pattern| %>
      <tr>
        <td><%= pattern.p1 %></td>
        <td><%= pattern.p2 %></td>
        <td><%= pattern.p3 %></td>
        <td><%= link_to 'Show', pattern %></td>
        <td><%= link_to 'Edit', edit_pattern_path(pattern) %></td>
        <td><%= link_to 'Destroy', pattern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pattern', new_pattern_path %>

app/views/patterns/new.html.erb
<h1>New pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', patterns_path %>

app/views/patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>P1:</strong>
  <%= @pattern.p1 %>
</p>

<p>
  <strong>P2:</strong>
  <%= @pattern.p2 %>
</p>

<p>
  <strong>P3:</strong>
  <%= @pattern.p3 %>
</p>

<%= link_to 'Edit', edit_pattern_path(@pattern) %> |
<%= link_to 'Back', patterns_path %>